### PR TITLE
Antichess evaluation tweaks

### PR DESCRIPTION
**Pull request by ianfab**
- tweak second order material bonus
- skip evaluation of initiative
- tweak threats evaluation

I think antichess Stockfish is now strong enough to consider using it on lichess. There are some issues when testing it against Sjeng in XBoard (Sjeng sometimes stops moving and loses on time, but usually in positions that are forced losses), so I can not tell yet exactly how strong it is. However, Stockfish seems to be able to compete with Sjeng and might even be stronger.

### CODE REVIEW

**Comment by ddugovic** [comment]
Great, I'll deploy it to [my instance](http://dugovic.mooo.com/) and import games between strong players & perform computer analysis to see how often it agrees with moves by strong players.

**Comment by ianfab** [comment]
@ddugovic Are there already any results?

**Comment by ddugovic** [comment]
Not yet as it took hours to deploy the engine.  I'll try again tonight.

**Comment by ianfab** [comment]
Ok, thanks for the quick update.

**Pull request merged**
