### PR TITLE
[RFC] More king safety

### PR DESCRIPTION
**Pull request by sf-x**
- This is a logical extension of SF's safety code to account for drops.
- This wasn't tested for playing anything other than crazyhouse.
- This wasn't tested against most recent version. `git merge-base master <commit>` gives 0ca93b2319 for both master and modified version that I tested.
- All tests were done from normal starting position, using experimental Winboard-AA package ( http://talkchess.com/forum/viewtopic.php?t=62331 ).
- All search speeds, unless stated otherwise, are from running
```
uci
setoption name UCI_Variant value crazyhouse
position startpos
go depth 13
```

Intel Atom: 112 kn/s for master, 109 kn/s for mod. Move Overhead set to 200 for both tests.
TC 450s with 1.5s increment, 1 thread (1 game at a time):
36 games. Mod as white: W=18 D=0 L=0, as black: W=7 D=1 L=10

TC 250s with 1s increment, 2 threads
12 games. Mod as white: W=5 D=1 L=0, as black: W=0 D=0 L=6
I will blame the bad result on insufficient time control.
Computer 2 (538 kn/s master, 490 kn/s mod, SF benchmark (`bench` command): master: 670 kn/s, mod: 653 kn/s), 32-bit builds
TC 120s with 0.5 s increment, 1 thread (1 game at a time):
100 games. Mod as white: W=50 D=0 L=0, as black: W=7 D=1 L=42 (Winboard results string: `+++++-+++++++++=+++++++-+++++++++++++++++++++++++++++++++++++++++++++++++++-+++++-+++-+-+++++++++++-`; + corresponds to white win; mod played white in the first game; during the long streak of +es computer was unattended)

### CODE REVIEW

**Comment by sf-x** [comment]
Evaluations by this mod are _crazy_. Perharps re-applying #145 atop is worth a test...

**Comment by ddugovic** [comment]
Thanks for the feedback and indeed my 4-core PC is running 4 LTC tests reapplying #145.  Preliminary results (out of 100 games at 60+1):
Score of KINGSAFETY Stockfish 041216 64 BMI2 vs Stockfish 031216 64 BMI2: 4 - 2 - 0  [0.667] 6
Score of KINGSAFETY Stockfish 041216 64 BMI2 vs Stockfish 031216 64 BMI2: 2 - 2 - 1  [0.500] 5
Score of KINGSAFETY Stockfish 041216 64 BMI2 vs Stockfish 031216 64 BMI2: 4 - 1 - 0  [0.800] 5
Score of KINGSAFETY Stockfish 041216 64 BMI2 vs Stockfish 031216 64 BMI2: 1 - 3 - 2  [0.333] 6

I am optimistic #145 will pass most of these LTC tests now that I have a better understanding of how to test; however I have yet to figure out how to make cutechess-cli use [crazyhouse.epd book](http://github.com/ianfab/books/blob/master/crazyhouse.epd) while testing.

**Comment by sf-x** [comment]
> my 4-core PC is running 4 LTC tests reapplying #145. 

Out of interest, why don't you run ONE test with `-concurrency 4`?

**Comment by sf-x** [comment]
I'd also like some comments about the change in this pull request, and what testing is needed.

**Comment by ddugovic** [comment]
> Out of interest, why don't you run ONE test with -concurrency 4?

I am unfamiliar with `cutechess-cli` and I am floundering searching for an example to follow, and I don't know the best way to do things. `-concurrency 4` makes more sense.

**Comment by ianfab** [comment]
@sf-x These winning and losing streaks with white and black, respectively, might have to do with the combination of using no opening book and a fixed time control. Have you checked at which point the games start to deviate?

**Comment by sf-x** [comment]
I'm not sure how to quantify it. I can upload games if you like. The test no. 1 (on Atom) has many games repeating nearly all the way to the end. No.2 games deviate about move 3-6 (but it's also inconclusive), I haven't checked No.3 games, but I think they are also similar.

**Comment by ianfab** [comment]
@sf-x You do not have to upload games, the information you gave is what I was interested in. It is important that games deviate before one side has a significant advantage, otherwise test results are not really useful. At move 3-6 the game should usually be far from decided.

**Comment by sf-x** [comment]
but 3-6 is for 12-games test, i.e. useless.

**Comment by sf-x** [comment]
For the other tests it's much larger. I have put the PGN here: https://github.com/sf-x/Stockfish/tree/pull_ks_pgn

**Comment by sf-x** [comment]
Just in case - I would not be surpised if this is a regression at 5s TC , or even at 10s TC.

**Comment by ddugovic** [comment]
Results so far at 60+1s (no opening book) strongly favor 30Nov2016 over (latest master + #145):

```
Score of KINGSAFETY Stockfish 041216 64 BMI2 vs Stockfish 031216 64 BMI2: 31 - 38 - 6  [0.453] 75
Score of KINGSAFETY Stockfish 041216 64 BMI2 vs Stockfish 031216 64 BMI2: 28 - 42 - 3  [0.404] 73
Score of KINGSAFETY Stockfish 041216 64 BMI2 vs Stockfish 031216 64 BMI2: 30 - 39 - 5  [0.439] 74
Score of KINGSAFETY Stockfish 041216 64 BMI2 vs Stockfish 031216 64 BMI2: 37 - 34 - 1  [0.521] 72
```

Assuming #145 is good this means the test is flawed and requires an opening book.  Note that (latest master + #145) contains two simplifications and I expected it to win most if not all of these tests.

**Comment by ddugovic** [comment]
Once that test fails (30Nov2016 is winning 60% to 40% again to my surprise) I will test #153 (current master versus master + patch) with 200 games at 240/60+0.1sec/move.

Once that regression fails we can still discuss how to use [SPSA](http://github.com/ianfab/spsa) to discover what constants to use (change the `* 2` to a `* N / 256` and discover what N-value makes sense).

**Comment by ddugovic** [comment]
#145 by itself does not pass.  Now testing as noted in my previous comment...

```
Score of KINGSAFETY Stockfish 041216 64 BMI2 vs Stockfish 031216 64 BMI2: 78 - 113 - 9  [0.412] 200
Elo difference: -61.43 +/- 48.02
Finished match
```

**Comment by ddugovic** [comment]
Branch `king_safety` (#145 + #153) passes by much more than 4 Elo:

```
Score of KINGSAFETY-153 Stockfish 051216 64 BMI2 vs Stockfish 051216 64 BMI2: 315 - 170 - 15  [0.645] 500
Elo difference: 103.73 +/- 31.36
Finished match

Score of KINGSAFETY-153 Stockfish 051216 64 BMI2 vs Stockfish 051216 64 BMI2: 120 - 75 - 5  [0.613] 200
Elo difference: 79.53 +/- 49.07
Finished match
```

**Comment by ddugovic** [comment]
Merged via #157.

**Pull request merged**
