### PR TITLE
RFC: Make "3check" and "threecheck" both valid variant names

### PR DESCRIPTION
**Pull request by sf-x**
"3check" is primary.

I'm not sure this change is correct, so please don't merge yet...

### CODE REVIEW

**Comment by niklasf** [comment]
What's the situation with GUIs and other software? Is `3check` more common?

(If you want to keep things tidy and go one step further by supporting *only* `3check` I wouldn't mind the compability break for lichess/fishnet).

**Comment by sf-x** [comment]
According to @ianfab cutechess (which is used to test changes to this version) doesn't support name "threecheck" at all. H.G.Muller, XBoard author, released a UCI-to-xboard wrapper which translates "threecheck" into "3check", I suspect, solely to accomodate this Stockfish.

**Comment by ianfab** [comment]
It perhaps makes sense to simply rename it to `3check` if there are no compatibility breaks except for fishnet.

**Comment by ddugovic** [comment]
I have no objection to the change as during my initial development I couldn't find UCI variant engines or interfaces which supported either name.

**Comment by sf-x** [comment]
Well, if only "3check" name is supported, that's fine too. I was trying to keep compatibility.

**Comment by ddugovic** [comment]
And while BC is laudable, in this case @niklasf maintains the largest repository and wouldn't mind the break.

Given that both WinBoard/XBoard and CuteChess now have UCI `3check` support, it seems `3check` has become the _de facto_ UCI standard and I have no objection to embracing it.

My initial selection of `threecheck` was based on a now-invalidated assumption that interface and engine designers would resist starting a variant name with a digit.

**Comment by ddugovic** [comment]
Closed with 965b0854874535719429ec24e7410effd296c2fb .

**Comment by ianfab** [comment]
I also renamed the opening book to `3check.epd`, so that there is no more naming confusion when submitting tests.

**Pull request closed without merging**
