### PR TITLE
dedicated FutilityMoveCounts for Crazyhouse

### PR DESCRIPTION
**Pull request by alwey**
This patch increases futility move counts for the crazyhouse variant. The values are stored in a dedicated array. The new values were determined by tests with a parametrized research version.

### CODE REVIEW

**Comment by ianfab** [comment]
In general the patch looks good to me, but I am confused why you do not simply use the values that have been verified to yield an improvement (you could verify functional equivalence to the tested version with `bench crazyhouse`). If you want to improve it further, I think it would be best to first commit the verified improvement and then test the new version against it.

**Comment by alwey** [comment]
ok, I am just working on a patch that includes the late move reduction change of divisor from 1.95 to 2.00 for crazyhouse. So this would be a version with verified settings. This patch is more complex. Nevertheless I am keen on seeing how an unaltered LMR set will perform.

**Comment by alwey** [comment]
This new version is functionally equivalent to the tested parameter set of the experimental version including LMR. Both versions give crazyhouse bench 6932855.

**Comment by ianfab** [comment]
Sorry, I do not understand which versions you are referring to. Since only one version had been tested on fishtest before my comment, I guess you are maybe referring to some local tests.

What I meant is that https://github.com/alwey/Stockfish/commit/4083b421fbd152a9b95123e84626e40ae8e8195d has been thoroughly tested and the tests were very successful, so IMO it would make sense to commit a version functionally equivalent to https://github.com/alwey/Stockfish/commit/4083b421fbd152a9b95123e84626e40ae8e8195d (taking the safe Elo gain - by the way, a great patch, congrats), and any version that is supposed to be an improvement over it should be tested against it.

**Comment by alwey** [comment]
No problem, I got it.

The new code is https://github.com/ddugovic/Stockfish/pull/369/commits/e77a7543080b35d95aa45983999ce43a497e967f  (https://github.com/alwey/Stockfish/commit/e77a7543080b35d95aa45983999ce43a497e967f). It is equivalent to  https://github.com/alwey/Stockfish/commit/4083b421fbd152a9b95123e84626e40ae8e8195d,

**Comment by ianfab** [comment]
I have not had the possibility to compare bench yet, but
```
o["lmr01"]                 << Option(19500, 1, 900000, on_lmr);
o["fmc00"]                 << Option(10000, -20000, 900000, on_lmr);
o["fmc01"]                 << Option(8000, -20000, 50000, on_lmr);
o["fmc02"]                 << Option(10000, -20000, 50000, on_lmr);
o["fmc03"]                 << Option(24000, -20000, 900000, on_lmr);
o["fmc04"]                 << Option(50000, -20000, 900000, on_lmr);

double d1 = int(Options["lmr01"]) / 10000.0;

double r = log(d) * log(mc) / d1;

double f0 = int(Options["fmc00"]) / 10000.0;
double f1 = int(Options["fmc01"]) / 10000.0;
double f2 = int(Options["fmc02"]) / 10000.0;
double f3 = int(Options["fmc03"]) / 10000.0;
double f4 = int(Options["fmc04"]) / 10000.0;

FutilityMoveCounts[0][d] = int(f3 + f0 * exp(f1 * d));
FutilityMoveCounts[1][d] = int(f4 + f0 * exp(f2 * d));
```
and
```
double r = log(d) * log(mc) / 2.00;

ZHFutilityMoveCounts[0][d] = int(10.0 + 0.5 * exp(0.8 * d));
ZHFutilityMoveCounts[1][d] = int(20.0 + 0.5 * exp(0.9 * d));
```
looks to me like they are different. I am bit confused.

**Comment by alwey** [comment]
You are looking at the first version. You are right, the  LMR part is missing here but the FMC part is identical. I amended the LMR change in the new and actual version https://github.com/alwey/Stockfish/commit/e77a7543080b35d95aa45983999ce43a497e967f .

Both versions just passed STC.

**Comment by alwey** [comment]
The Options code https://github.com/alwey/Stockfish/commit/4083b421fbd152a9b95123e84626e40ae8e8195d is only experimental, it cannot be used for production. 

The code with dedicated arrays https://github.com/alwey/Stockfish/commit/e77a7543080b35d95aa45983999ce43a497e967f is intended for production.

**Comment by alwey** [comment]
Ah, now I see the reason of the confusion. My set in the tests intentionally has overridden the default values: 
`new_options	Hash=32 Move Overhead=100 lmr01=20000 fmc00=5000 fmc01=8000 fmc02=9000 fmc03=100000 fmc04=200000`

**Comment by ianfab** [comment]
Ah, I did not pay attention to the settings. Thanks for clarifying.

**Comment by ddugovic** [comment]
Cool, glad to see this improvement!

Long-term I wonder if it would be useful to augment the existing arrays (adding a variant dimension) and to add a `Variant` parameter to function `reduction` (perhaps allowing the compiler to cleverly optimize search per-variant if we're lucky).

**Pull request merged**
