### PR TITLE
Implement KR vs. KP endgame for atomic chess

### PR DESCRIPTION
**Pull request by ianfab**
KR vs. KP is a tricky endgame that can not be won without knowing the long-term plans. The implementation resulted from [this thread](https://lichess.org/forum/team-atomic-chess-theoreticians/check-out-my-article-about-atomic-endgames-please-give-feedback).

This endgame is very rare, so there certainly is no gain in general playing strength, but it might be good for analysis. Since I anyway had already done the work, I thought I open this PR to discuss whether it is considered useful.

### CODE REVIEW

**Comment by ddugovic** [comment]
We should consider a way to test endgame position playing strength (perhaps at first for very rare endgames, eventually for more common endgames).

**Comment by ianfab** [comment]
This topic has also been discussed several times for official stockfish, but it seems to be hard to come up with a good solution. You at least need a large set of positions of a certain endgame. However, the choice of this set will probably influence the result and the question also is whether you do not miss the most important part by not testing conversions to that endgame, since that will probably have the biggest impact on playing strength, not playing out the endgames itself. E.g., if you teach it how to win an endgame, but the evaluations are lower than before, it might be that it prefers to go into other endgames and basically avoids the positions it has learned to play well.

Having a realiable test would be very nice, but I think it is not an easy task to set it up.

**Comment by alwey** [comment]
I trust this forum more to come up with a solution than the other one.

**Comment by ddugovic** [comment]
Hmm... OK, testing endgame _playing_ strength is too challenging.

I think it's still appropriate to have a way to test something here, for two reasons:
* Testing for future regressions is of some benefit
* New tests are useful for trying new ideas (possibly to less specific endgames than KR versus KP)

**Comment by ianfab** [comment]
In my opinion it is only practical to do systematic endgame testing if we have a position generation algorithm that can at least be partly automated in a similar way as I did it for opening books. Collecting hundreds of positions for several endgame types in a couple of variants seems impractical.

The question is whether there is a way to automatically generate sensible endgame positions (i.e., not just randomly placing the pieces) for given material configurations or given number of pieces. One inefficient way would be to generate self-play games from the starting position or an opening book (instead of generating the games ourselves, we could of course also use databases if available), filter the positions by certain criteria, and then take a subsample of them.

**Comment by alwey** [comment]
> In my opinion it is only practical to do systematic endgame testing if we have a position generation algorithm that can at least be partly automated in a similar way as I did it for opening books. Collecting hundreds of positions for several endgame types in a couple of variants seems impractical.

Good point. The harvesting of endgame and midgame positions should really be (both energy and time) efficient.

> The question is whether there is a way to automatically generate sensible endgame positions (i.e., not just randomly placing the pieces) for given material configurations or given number of pieces. One inefficient way would be to generate self-play games from the starting position or an opening book (instead of generating the games ourselves, we could of course also use databases if available), filter the positions by certain criteria, and then take a subsample of them.

I think this is a viable method, using game databases and filters. One might ask pgn-extract and Marco Costalba's PGN scanner Stockfish for help, and your (@ianfab's) book-generator to expand found positions into families of positions to make small footprints bigger. For standard chess there are vast databases for both master games and super-engine games. And lichess.org has some games for variant play.

**Comment by ddugovic** [comment]
I'd like thoughts on 11c9c1ab6d483290bb16b763a5938dffe01e6bae which detects when either (or both) players cannot win due to a fortress draw, a circumstance which many atomic players have observed or even experienced!

In my (limited) testing, that patch is both fast and accurate (and I don't see any faster or more accurate way to rewrite it), yet it doesn't much improve Elo in STC self-play.  But even given how (relatively to K+R versus K) common fortress are, I wonder... maybe VSTC testing would put more emphasis on evaluation and less emphasis on search?

**Comment by ianfab** [comment]
@ddugovic I do not understand which positions the second condition tries to cover. Could you give an example?

I think it is very unlikely to see any measurable improvement without using a book of late middlegame or endgame positions. The above mentioned filtering of databases (or stockfish self-play games) still is  the best idea I can come up with. With python-chess it should be relatively easy to iterate through PGNs and report positions that match some criteria like a certain material constellation. If I find the time, I will try that out.

**Comment by ddugovic** [comment]
@ianfab I am trying to cover symmetrical pawn positions like [8/6k1/7p/p3p1pP/4P1P1/8/P3B3/6K1 w - - 0 1](https://lichess.org/analysis/atomic/8/6k1/7p/p3p1pP/4P1P1/8/P3B3/6K1_w_-_-) where a passed pawn cannot be created (with or without help from the bishop).

**Comment by ianfab** [comment]
@ddugovic But that is already covered by the first if-statement, so what does the [second one](https://github.com/ddugovic/Stockfish/commit/7aa5cc426100ad27910a8fe8713b7aee0af84506#diff-e88e03386a215910d76a232ae9603922R1639) do?

**Comment by ddugovic** [comment]
@ianfab Ah, that's to try to handle asymmetric positions where the player with the bishop cannot win such as [6k1/6p1/7p/8/8/8/6BP/6K1 w - - 0 1](https://lichess.org/analysis/atomic/6k1/6p1/7p/8/8/8/6BP/6K1_w_-_-).

**Comment by ianfab** [comment]
@ddugovic I think the condition is much too broad. It evaluates to true even for positions like [4k3/8/p7/P2p1p1p/3P1P1P/8/4B3/4K3_w_-_-](https://lichess.org/analysis/atomic/4k3/8/p7/P2p1p1p/3P1P1P/8/4B3/4K3_w_-_-), so I think you should rather replace the `!pe->pawn_asymmetry()` in the first if statement if you want to include positions where the weaker side has one pawn for the bishop. A potential test with a book of endgame position must be able to find such issues.

**Comment by ddugovic** [comment]
Thanks for the suggestion.  I'm still confused however:

```
            if (   !pe->pawn_asymmetry()
                && !pe->pawns_on_same_color_squares(~strongSide, pos.square<BISHOP>(strongSide)))
                return SCALE_FACTOR_DRAW;

            if (! ((0xFF ^ pe->semiopen_files(strongSide)) & pe->semiopen_files(~strongSide)))
                sf = ScaleFactor(8); // Possible fortress
```

I think `SCALE_FACTOR_DRAW` is only used in positions where the bishop cannot capture the pawns, whereas `ScaleFactor(8)` is used in positions which are not easily proven to be fortress positions (and indeed search may discover a win)... but that said, a fortress is only possible if the weaker side has the same number of pieces (or more) than the stronger side so `ScaleFactor(8)` is being applied incorrectly.

**Comment by ianfab** [comment]
If the stronger side has no unopposed pawns and the weaker side's pawns all are on the opposite color of the bishop, then I think the only possible way to win could be zugzwang by stalemating the king if not all pawns are blocked.

If you want to detect fortress positions where some pawns are on the bishop's color, I think you need a more complex logic.

**Comment by mtaktikos** [comment]
Hallo Fabian,

ich bin ganz neu in der Diskussion bei github.

Habe beim gewöhnlichen Stockfish (ohne Varianten) eine Version 
implementiert, die Nullmove abschaltet und contempt erhöht,
sie schlägt sich erstaunlich gut beim Lösen taktischer Schachprobleme, 
viel besser als die Matefinder.
Weiterhin habe ich eine Version, die das Patt für denjenigen, der keine 
Züge mehr hat, als Niederlage betrachtet - sie soll in etwa das Spiel
von AlphaZero nachvollziehen, das seine Gegner "erstickt".  Unter 
github/mtaktikos zu laden


Was noch als einfache Veränderungen zu SF Multivariant zu sagen wäre, 
wäre die Implementation einiger Schachvarianten aus dem Server "Brainking":
*  Massacre Chess. Ließe sich recht einfach aus Giveaway Chess 
implementieren, nur andere Anfangsstellung und das Spiel ist zu Ende, 
wenn keine Schlagzüge mehr vorhanden sind.
*  Recycle Chess. Wie Loop Chess, nur darf man seine eigene Figuren schlagen
* Amazon Chess. Hier darf die Dame auch Springerzüge ausführen und heißt 
Amazone.
Das fällt mir ein, wenn es darum geht, mit möglichst wenig veränderten 
Zeilen in SF Multivariant neue Schachvarianten zu implementieren.

Mit freundlichen Grüßen,
Michael Taktikos
Haubachstr. 46
22765 Hamburg

**Comment by ianfab** [comment]
@mtaktikos Hallo Michael, danke für deine Vorschläge. Wenn möglich wäre es gut die Diskussion auf Englisch weiterzuführen, damit andere mitlesen und beitragen können. Außerdem würde ich vorschlagen, dass du einen separaten "[Issue](https://github.com/ddugovic/Stockfish/issues)" aufmachst damit wir deine Vorschläge dort diskutieren können, denn es ist hilfreich für die Übersichtlichkeit und das Wiederfinden von Diskussionen, wenn unterschiedliche Themen getrennt werden.

Falls das für dich in Ordnung ist, würde ich dann später ausführlicher auf Englisch antworten, sobald du einen separaten Issue aufgemacht hast.

**Comment by mtaktikos** [comment]
Sry for the mistake, it was my first comment in github ;)
Of course we can continue in a new issue and in English

**Comment by ianfab** [comment]
@mtaktikos No problem, and thanks.

**Comment by ianfab** [comment]
@mtaktikos I was assuming that you open the issue. No problem if you did not have the time yet, I just want to clarify.

**Comment by ddugovic** [comment]
To my astonishment, https://github.com/official-stockfish/Stockfish/pull/1939#commitcomment-31858096 gives us an example to follow in terms of how to test rare, usually-drawn endgames already covered by syzygybases.  I still doubt upstream will merge that PR but if they do, I guess it's OK for us to follow suit.

**Comment by ddugovic** [comment]
I'll attempt to generalize this for K+R+Ps versus K+Ps, which seems to be a large issue:
https://lichess.org/mi5V4SJM#36

**Pull request closed without merging**
