### PR TITLE
[RFC] Enable tablebase probing during search for atomic and giveaway

### PR DESCRIPTION
**Pull request by ianfab**
Thanks to @niklasf's great work on the probing code, I think we can now enable tablebase probing during search for atomic and giveaway chess.

### CODE REVIEW

**Comment by niklasf** [comment]
Awesome. If you want to test this you can download the tables I generated here:

* https://syzygy-tables.info/atomic/
* https://syzygy-tables.info/suicide/ (here just use pawnless and giveaway tables. 6 piece giveaway tables with pawns are still beeing generated)

**Comment by ianfab** [comment]
Thanks a lot. So far it worked fine in all positions I have tested, including adjacent kings in atomic chess and positions without kings in giveaway. Analyzing the starting position in giveaway resulted in tens of thousands of tablebase hits (even though I have only downloaded parts of 2-5 men TBs) and no error has occurred yet.

**Comment by ddugovic** [comment]
I see the [RFC] title, but I see no reason not to merge this understanding that further improvements may be possible...

**Comment by ianfab** [comment]
Yes, I think it can be merged. So far I have not encountered any problems when using atomic and giveaway TBs.

**Pull request merged**
