### PR TITLE
Split out variant-specific evaluation terms

### PR DESCRIPTION
**Pull request by ianfab**
This is not really a merge request, but just to provide some code to discuss the idea. What do you think about splitting out variant-specific evaluation terms that do not exist for standard chess (mostly related to additional winning conditions)?

This commit does not change `bench all`.

### CODE REVIEW

**Comment by ddugovic** [comment]
Hm... the only changed data structure is `Score scores[TERM_NB][COLOR_NB];` and this separate term/function might actually improve performance.

There could be confusion about what is supposed to be variant-specific, although sometimes (e.g. King of the Hill variant ending) both the normal ending and the variant ending are common & it could be useful to see the King safety and Variant terms separated.

I'm trying to understand how to reconcile this idea with the current mess of how the terms are organized...

**Comment by ianfab** [comment]
The more detailed eval debug output might also be useful, but the idea is mainly about code readability and maintainability. No matter where we put these terms (into passed pawns, threats, king safety, etc.), they always seem to be misplaced, and since they do not share code/variables with those other terms (that is what could be considered the main criteria for "variant-specific"), I think it would be nice to separate them in some way (whether we use one method for all variant-specific terms with ifs or a switch, separate methods, templates or something else is then only a minor detail).

**Comment by ddugovic** [comment]
After much pondering, I completely agree:

> No matter where we put these terms (into passed pawns, threats, king safety, etc.), they always seem to be misplaced, and since they do not share code/variables with those other terms... it would be nice to separate them in some way.

**Comment by ianfab** [comment]
I rebased the changes. For some reason `bench all` is changed by this PR. I will check whether this is caused by the code changes themselves or by undefined behavior.

**Comment by ddugovic** [comment]
@ianfab I recently changed support for horde chess with colors reversed (which is a non-functional change for normal horde positions) to use `relative_rank` which is used elsewhere for the same purpose:

https://github.com/ddugovic/Stockfish/commit/57e93dfefabc63313bd4f842d7e8ef3e3ec78334#diff-e88e03386a215910d76a232ae9603922R1336

**Comment by ianfab** [comment]
@ddugovic Thanks, I will fix that. It apparently got lost during rebasing. I unfortunately did not have the time to investigate the bench issues yet.

**Comment by ianfab** [comment]
@ddugovic I reapplied the changes that were lost during rebasing, and I rebased again. I now get the same `bench all` (29856786) for master and this branch.

**Comment by ddugovic** [comment]
@ianfab Excellent, this non-functional change looks good to me!

**Pull request merged**
