### PR TITLE
Make weight changes to evaluate.cpp

### PR DESCRIPTION
**Pull request by stockfishdeveloper**
Hi Dan,
This is David from the Downers Grove Chess Club.
There are a couple of changes I think that should be made to Evaluate.cpp; please take a look at them and see if they are better. I have not been able to test them over thousands of games and I cannot use Fishtest because I have a single-core computer.

Thanks Dan!
Dave

### CODE REVIEW

**Comment by ddugovic** [comment]
Hi David!  I have looked at the code and if official-stockfish accepts the changes, so too shall I!  I have spent hours unsuccessfully attempting to install fishtest; and looking at [fishtest documentation](http://stockfishchess.org/get-involved/) and [tutorial](http://github.com/glinscott/fishtest/wiki/Creating-my-first-test) and [live test site](http://tests.stockfishchess.org/tests/run) still things look a bit daunting.  I'll register on their [forum](http://groups.google.com/forum/?fromgroups=#!forum/fishcooking) and see if they can help me generate a test for volunteers to run, and/or install fishtest myself.

I know that official-stockfish tunes weights through many tests consisting of thousands of games, so I'm hesitant to change any code if either of two factors are missing:

1.  Evidence suggesting a need for change -- I'm uncertain how these numbers (in combination with everything else Stockfish does in its evaluation function) are better or worse; or whether future official-stockfish changes (which I will continue to merge into this fork) will break this change!
2.  A clear plan to test the change -- I'll try the forums but I'd be surprised if fishtest worked on my computer.  Maybe I could try running game analyses and discover whether their accuracy increases in some way due to the changes.

**Comment by stockfishdeveloper** [comment]
Ok, I have been able to install Fishtest and run it without any problems... the only problem is that Fishtest requires at least two cores but my comp has only one. If you have any trouble installing Fishtest, let me know what you are stuck on. I'm sure I can help because I know Python pretty well(Fishtest is written in Python). By the way, I've been having some trouble with the Zthreads library(for C++). It's a threading library that I hope to use for my chess engine. Would you perhaps have any experience with this particular library or threading in general?
Thanks,
Dave

**Comment by ddugovic** [comment]
Sorry, I was unclear in my previous comment.  After installing FishTest I had difficulties running it.  Currently my home server which I use for development is broken, but once I un-break it and advise which of the [dozen post-installation configuration steps](http://github.com/glinscott/fishtest/wiki/Running-the-worker-on-Linux) I had difficulty with.  Possibly things may go better (or worse) as that server has migrated from Virt-Manager/KVM-based CentOS 7 to Vagrant/Virtualbox-based Ubuntu 15 and I'm still working out all kinds of permissions and firewall problems.

I still have no idea or understanding how or why the numbers provided by the expert are in any way superior to those tested thousands of times by [the Stockfish development team](http://github.com/official-stockfish).

**Comment by niklasf** [comment]
It appears that official-stockfish has retuned and dropped `Threats` in the meantime: 9fac5774f414ec4a2e86c6. Your patch will no longer apply to the official master branch (or may even be obsolete).

**Comment by stockfishdeveloper** [comment]
I have a fishtest account and I tried to create a test by clicking on "New". Which fields must be filled in for the test? For the "Test Repo" field, should I enter my fork of Stockfish(stockfishdeveloper/Stockfish)?
Also, how do you determine the "Bench" field? What do I put in the "Test branch", "Test signature", "Base branch" and "Base signature" fields? I would love to help with the development of Stockfish and I have a few pretty good ideas, but I have never been able to create a test. Please help me create my first test.
Thanks!
stockfishdeveloper(David)

**Comment by niklasf** [comment]
https://github.com/glinscott/fishtest/wiki/Creating-my-first-test seams to be a pretty good guide.

**Comment by stockfishdeveloper** [comment]
Alright, I'll take a look. Thanks.
David

**Comment by stockfishdeveloper** [comment]
By the way, Either of you(Dan or niklasf) do either of you have any experience with the Zthreads threading library? I'm trying to  use it in my own chess engine. Mainly I'm concerned with the speed of the mutexes; are they fast or should I just go with the C++ standard threading?
Thanks,
Dave

**Comment by stockfishdeveloper** [comment]
Also, in the creating tests guide, it says "navigate to the Stockfish directory" Which directory does it mean? My copy of the repository, the official Stockfish repository, or what?
Thanks,
Dave

**Comment by ddugovic** [comment]
Excellent suggestions @niklasf ; I thought it might be possible to submit tests to the cluster rather than creating my own fishtest node, but as I've never used that cluster before I was unsure!

I am reading [the guide](https://github.com/glinscott/fishtest/wiki/Creating-my-first-test) and I see no mention of "navigate to the Stockfish directory".  You are interested in running a Standard Test...

Yesterday I didn't make the connection between test branch, test signature, and test repository; and base branch & base signature.  Today it seems to make sense so [I created a test](http://tests.stockfishchess.org/tests/view/56705d410ebc592d552a4178) but maybe did it incorrectly...
test branch: `master`
test signature: `d6e84a7`
test repository: `https://github.com/stockfishdeveloper/Stockfish`
base branch: `master`
base signature: probably `8315620`

**Comment by ddugovic** [comment]
@stockfishdeveloper I have no idea what `Zthreads` are and I don't understand why they would be preferable to standard, well-documented [POSIX threads](https://computing.llnl.gov/tutorials/pthreads/).

**Comment by stockfishdeveloper** [comment]
Well, the reason I wanted to use Zthreads is because they have been designed to be used only on Windows. This should make the library more optimized for Windows than POSIX because POSIX is muli-platform, right?

**Comment by stockfishdeveloper** [comment]
By the way, @niklasf, I was the person that motivated the test that @ddugovic created; I have never been able to create a test.

**Comment by ddugovic** [comment]
> This should make the library more optimized for Windows than POSIX because POSIX is muli-platform, right?

I wanted to learn more about this so I searched both Google and Wikipedia.  Both claim that zthreads is "An advanced object-oriented, cross-platform C++ threading and synchronization library.".  Wikipedia [goes further](https://en.wikipedia.org/wiki/ZThreads):

> ZThreads is a cross-platform high-level object-oriented C++ library, which provides an interface to application programming interface (API) threads for POSIX Pthreads and Windows API threads.

so if anything, zthreads appears to be an additional layer on top of other threading libraries!  If there's any evidence suggesting that zthreads performs well, please inform me!

By the way, if you're looking to optimize your program, I recommend first reading all [Jeff Atwood's articles on the subject of optimization](http://lmgtfy.com/?q=jeff+atwood+optimization).

**Comment by stockfishdeveloper** [comment]
Ok Dan, Thanks for the optimization link. Bruce Eckel(who wrote Thinking in C++) apparently thought that Zthreads was good enough to use, albeit the book was written before threading became part of the C++ standard. I was hoping for a smaller threading library so that it would not increase the size of the executable much. I seem to have Zthreads working now, so I'll let you know how they are performance-wise.

Thanks,
Dave

**Comment by ddugovic** [comment]
Great!

Rest assured that if `official-stockfish` accepts your PR, I will merge from upstream and include the change in this repository.

**Pull request closed without merging**
