### PR TITLE
Three check variant added

### PR DESCRIPTION
**Pull request by ThyChief**
A notice for the concerned:
Although it wasnt a problem while testing with any popular interface like fritz, you have to set the position for white if you are starting a new game with the uci query: position startpos moves
otherwise it will play standard chess and not consider the variant

### CODE REVIEW

**Comment by ornicar** [comment]
now that sounds great.

**Comment by ddugovic** [comment]
Excellent!  I've merged your change and look forward to tuning and testing it!

**Comment by ddugovic** [comment]
I'm merging upstream changes (from the official repository) into this project and encountering many merge conflicts due to whitespace changes.  Please try to follow the coding style of the original authors next time.

**Comment by ddugovic** [comment]
After merging official changes, some testing, and a few changes of my own, all looks good!  I recommend that @ornicar test and/or deploy at his discretion.

**Comment by ornicar** [comment]
I'm now deploying this repo master to all lichess A.I. nodes. I'm late, and my excuse is that stockfish added some extra output that was breaking my parser, but now everything is fine. 32 instances deployed so far, ~30 more to go.
Threecheck option soon to be deployed on lichess.

Congrats for your great work guys!

**Pull request merged**
