### PR TITLE
Implement losers chess

### PR DESCRIPTION
**Pull request by ianfab**
Move generation and validation could not be verified with perft yet, because I do not have numbers to compare to. Looking at PVs (e.g. e2e4 b7b5 f1b5 b8c6 b5c6 h7h5) there apparently are bugs, so please do not merge it yet.

### CODE REVIEW

**Comment by ddugovic** [comment]
I [fixed](http://github.com/niklasf/Sjeng/pull/1) Sjeng perft.

**Comment by ianfab** [comment]
I have fixed a bug regarding pinned pieces (e.g. in the PV above) and it looks better now. If I have time to, I will compare perft numbers with your fixed version of Sjeng's perft.

**Comment by ianfab** [comment]
There were two bugs with evasions, because I copied the code from giveaway, which does not need to deal with evasions. Perft numbers are now in agreement with Sjeng up to depth 6, but differ for depth 7:

depth | Sjeng | Stockfish
-- | -- | --
3 | 8067 | 8067
4 | 152955 | 152955
5 | 2723795 | 2723795
6 | 46038682 | 46038682
7 | 757408169 | 757349642

**Comment by ddugovic** [comment]
Stockfish `perft` results look good to me.  (I replicated the Sjeng test results and agree Sjeng is flawed.)

**Comment by ianfab** [comment]
I played a few games against Stockfish using XBoard and while it is quite weak (it lost 1-2 against me even though I had not played losers before), it at least played legal moves and found forced wins/losses several moves ahead.

I shall add some comments to `can_capture_losers`, because it is essential for the implementation of losers.

**Comment by ddugovic** [comment]
Everything looks good to me.  I see the [WIP] tag but this seems to satisfy #110; should I merge this?

**Comment by ianfab** [comment]
I fixed another bug, but now I think it is mergeable.

**Pull request merged**
