### PR TITLE
Simplify crazyhouse king safety evaluation

### PR DESCRIPTION
**Pull request by ianfab**
Remove the general factor of 2 and instead tweak the constants.

LLR: 2.98 (-2.94,2.94) [0.00,20.00]
Total: 258 W: 155 L: 97 D: 6

### CODE REVIEW

**Comment by MichaelB7** [comment]
hmmm ..my quick test on this pr was not as productive:
Stockfish CrazyHouse-3 had pr #145

```
Rank Name                                        Rating   Δ     +    -     #     Σ    Σ%     W    L    D   W%    =%   OppR 
  ---------------------------------------------------------------------------------------------------------
   1 Stockfish Crazy-House-1 64 POPCNT (UCI2WB)   3230   0.0   21   21  1200  854.5  71.2  844  335   21  70.3   1.8  3035 
   2 Stockfish CrazyHouse-3 64 POPCNT (UCI2WB)    3129 101.2   27   27   600  230.0  38.3  223  363   14  37.2   2.3  3230 
   3 Stockfish 251116 64 POPCNT (UCI2WB)          2940 189.0   32   32   600  115.5  19.2  112  481    7  18.7   1.2  3230 
```

**Comment by ianfab** [comment]
@MichaelB7 I am currently testing with and without an opening book, but in both tests it is ahead so far. I will post the final results later.

**Comment by ianfab** [comment]
Here are my results:
```
without book:
ELO: 48.25 +-21.4 (95%) LOS: 100.0%
Total: 1000 W: 555 L: 417 D: 28

with book:
ELO: 18.08 +-20.9 (95%) LOS: 95.5%
Total: 1000 W: 497 L: 445 D: 58
```

**Comment by alwey** [comment]
@MichaelB7 @ianfab : Which time controls did you use?

**Comment by ianfab** [comment]
I have used my [testing script](https://github.com/ianfab/variantfishtest) with default settings, which means that the increment is 100ms and the initial time varies between 100ms and 10s (to avoid repeatedly getting the same games). However, I doubt that an evaluation patch performs that much different just because of different time controls.

**Comment by alwey** [comment]
@ianfab : Thank you. I am currently testing some recent versions with 10s + 0.1s increment and with 30s + 0.3s increment. I noticed a strong dependency on time control. (So for at 10s+0.1s the version with patch #145 is way better than all versions with patch #136 and older.)
I have to do the 30s+0.3s test and then go back and test the previous version without #145.

**Comment by ianfab** [comment]
@alwey Thanks for your reply. Could you please quantify in Elo, percent, or the like what you mean by strong dependency?

I am aware that my testing has its weaknesses and I think the (small/missing) opening books and time control are the most important. In the beginning, many patches were worth several hundred Elo, so the exact testing conditions did not matter at all and I focused on writing code, but it might now be time refine the testing to get more accurate results in order to avoid regressions and detect small improvements.

**Comment by alwey** [comment]
@ianfab : I already had a look at your script and book a week ago. I realized that it is very difficult to get enough data. And you are working on many variants and settings and indeed your approach works well as long the differences are tens and hundreds of elo. So - well done. Later on it will probably be necessary to reiterate but this will take longer and need more computing resources when the improvements are smaller.

I will post my test results here shortly after #145 has played 1000 games.

**Comment by alwey** [comment]
Update added version without PR #145, defined pool average as zero.
Test results (10s + 0.1s/move, 16MB Hash, opening 2moves_v1.epd, 1 core i5-5200U, linux-4.4):
```
   # PLAYER                      :  RATING  ERROR  POINTS  PLAYED   (%) Comment
   1 Stockfish-176ffa9           :     106     18   815.0    1243  65.6 301116 (T)
   2 Stockfish 011216 64 BMI2    :     100     17   859.0    1323  64.9 45b1958 (T)
   3 Stockfish-e51f24a           :     -32     14   845.0    1822  46.4 051116 (T)
   4 Stockfish 291116 64 BMI2    :     -34     13  1056.5    2226  47.5 fc3c7a6 (T)
   5 Stockfish-3813ff9           :     -61     24   298.5     648  46.1 041116 stable
   6 Stockfish-465c9aa           :     -79     14   772.0    2030  38.0 instable (D, T)

White advantage = 20.53 +/- 5.36
Draw rate (equal opponents) = 2.56 % +/- 0.23

Chronological order

   # PLAYER                      :  RATING  ERROR  POINTS  PLAYED   (%) Comment
   5 Stockfish-3813ff9           :     -61     24   298.5     648  46.1 041116 stable
   3 Stockfish-e51f24a           :     -32     14   845.0    1822  46.4 051116 (T)
   6 Stockfish-465c9aa           :     -79     14   772.0    2030  38.0 061116 instable (D, T)
   4 Stockfish 291116 64 BMI2    :     -34     13  1056.5    2226  47.5 fc3c7a6 (T)
   1 Stockfish-176ffa9           :     106     18   815.0    1243  65.6 301116 (T)
   2 Stockfish 011216 64 BMI2    :     100     17   859.0    1323  64.9 45b1958 (T)


(D) disconnects
(T) time forfeits

```

**Comment by ianfab** [comment]
Sor your results seem to confirm that this PR at least is no significant regression.

**Comment by alwey** [comment]
@ianfab: Yes, at 10 s + 0.1 s we can not say it is a regression. Testing with 30 s + 0.3 s now.

**Comment by alwey** [comment]
Next test will be Stockfish-176ffa9 .
 
Test results (30s + 0.3s/move, 16MB Hash, opening 2moves_v1.epd, 1 core i5-5200U, linux-4.4):
```
   # PLAYER                      :  RATING  ERROR  POINTS  PLAYED   (%)  Comment
   1 Stockfish 011216 64 BMI2    :     129     21   714.0    1004  71.1  45b1958 (T)
   2 Stockfish-e51f24a           :       2     22   332.5     741  44.9  051116
   3 Stockfish 291116 64 BMI2    :       0     18   517.0    1082  47.8  fc3c7a6 (T)
   4 Stockfish-3813ff9           :     -35     33   153.5     341  45.0  041116 stable
   5 Stockfish-465c9aa           :     -96     26   175.0     616  28.4  061116 instable (D, T)

White advantage = 19.42 +/- 8.49
Draw rate (equal opponents) = 2.88 % +/- 0.40

Chronological order

   # PLAYER                      :  RATING  ERROR  POINTS  PLAYED   (%)  Comment
   4 Stockfish-3813ff9           :     -35     33   153.5     341  45.0  041116 stable
   2 Stockfish-e51f24a           :       2     22   332.5     741  44.9  051116
   5 Stockfish-465c9aa           :     -96     26   175.0     616  28.4  061116 instable (D, T)
   3 Stockfish 291116 64 BMI2    :       0     18   517.0    1082  47.8  fc3c7a6 (T)
   1 Stockfish 011216 64 BMI2    :     129     21   714.0    1004  71.1  45b1958 (T)

(D) disconnects
(T) time forfeits

```

**Comment by alwey** [comment]
@MichaelB7 : I confirm your observation.
@ianfab  @ddugovic : There were (at least) two crazyhouse regressions in November. It seems #145 is helping for short searches but does not work well for "longer" time controls. Amazing progress in spite of this however, congratulations!

**Comment by ddugovic** [comment]
I'm somewhat confused by `Stockfish Crazy-House-1 64 POPCNT (UCI2WB)` in @MichaelB7 's comment; I assume that refers to the commit previous to #145 merge.

I assume from @alwey 's test that `Stockfish-176ffa9` refers to the commit previous to #145 merge and `Stockfish 011216 64 BMI2` refers to the commit after #145 merge (probably downloaded from niklasf/Stockfish releases).

I further assume time forfeits are not using `Move Overhead=1000` setting will be used in the championship, so I should not panic about the `(T)` indicator.  I don't know what causes disconnects; perhaps the test was aborted?  I honestly don't know.

I think I understand @alwey 's conclusion about #145 , although if I'm reading the "Chronological order" results correctly the strongest Stockfish at 30s + 0.3s/move (on that machine) is `Stockfish-176ffa9` and that there are at least two regressions costing a total of ~200 Elo.

**Comment by MichaelB7** [comment]
I believe #145 was supposed to be a simplification, but it actually changed the node count when running bench. I ran another 1000 games and it is still coming up regressive by about 100 ELO.  I'm not familiar with the other regressive patch. Stockfish Crazy-House-1 64 POPCNT (UCI2WB) is the version prior to #145.

**Comment by ianfab** [comment]
This patch was supposed to simplify the code in some way, but I was aware that it is a functional patch, which is why I tested it in the first place. Admittedly, the title is misleading. Since there is evidence that it is a regression, I would be ok with reverting this PR.

Patches should probably be tested in a two-step procedure just like on fishtest to avoid such regressions. However, I am currently not sure about time controls and SPRT bounds, since tests should finish in a reasonable amount of time. At least I now have a first version of automatically generated books that presumably improve reliability of test results.

**Comment by ddugovic** [comment]
I admit ignorance on how the tests work, but it sounds like everyone favors reverting this PR so I'll do that...

**Comment by alwey** [comment]
@ddugovic : Your interpretation of my postings is correct in all aspects. I compiled the versions from my clone of your stockfish master branch. I checked out the target commits e.g. 176ffa9 and compiled with ARCH=x86-64-bmi2. I used a recent version of cutechess-cli for testing.

Currently I am testing Stockfish-176ffa9 (which is indeed @MichaelB7  Crazy-House-1 64 POPCNT albeit with bmi2 instructions) against its successor. It looks like the regression is even bigger at 120s + 1.2s/move (in the range 50-70 elo).

The disconnects result from a severe problem with the version 465c9aa: I see protection violation traps logged in my syslog.

**Comment by ddugovic** [comment]
Thanks for the information.  The last time I observed a memory-related error was before 1118898 (discussed at #84), but 465c9aa chronologically comes *after* that fix so the disconnects result from a severe problem which I do not recall being fixed!

@MichaelB7 submitted #150 which I merged via a9938b7 (increasing 7th-rank pawn drop by +15 as such moves tend to be crushing).

**Comment by alwey** [comment]
Just to complete this test:
Test results (120 s + 1.2 s/move, 16 MB Hash, opening 2moves_v1.epd, 1 core i5-5200U, linux-4.4):

   ```
Score of Stockfish-176ffa9 vs Stockfish 011216 64 BMI2: 157 - 101 - 15  [0.603] 273

   # PLAYER                      :  RATING  ERROR  POINTS  PLAYED   (%)  CFS(%)  OppAvg
   1 Stockfish-176ffa9           :      73     41   164.5     273  60.3     100       0
   2 Stockfish 011216 64 BMI2    :       0   ----   108.5     273  39.7     ---      73

White advantage = 23.89 +/- 21.08
Draw rate (equal opponents) = 5.64 % +/- 1.40

   ```

**Pull request merged**
