### PR TITLE
Fix #348: atomic chess castling

### LINKED ISSUE #348: Atomic960 castling with b rook shielding attack from a file
This doesn't have very high priority, since Atomic960 is rather rare. Input:

```
setoption name uci_variant value atomic
setoption name uci_chess960 value true
position fen 8/8/8/8/8/8/2k5/rR4K1 w Q - 0 1
d
perft 1
```

Output:

```
Stockfish 140517 64 BMI2 by T. Romstad, M. Costalba, J. Kiiski, G. Linscott

 +---+---+---+---+---+---+---+---+
 |   |   |   |   |   |   |   |   |
 +---+---+---+---+---+---+---+---+
 |   |   |   |   |   |   |   |   |
 +---+---+---+---+---+---+---+---+
 |   |   |   |   |   |   |   |   |
 +---+---+---+---+---+---+---+---+
 |   |   |   |   |   |   |   |   |
 +---+---+---+---+---+---+---+---+
 |   |   |   |   |   |   |   |   |
 +---+---+---+---+---+---+---+---+
 |   |   |   |   |   |   |   |   |
 +---+---+---+---+---+---+---+---+
 |   |   | k |   |   |   |   |   |
 +---+---+---+---+---+---+---+---+
 | r | R |   |   |   |   | K |   |
 +---+---+---+---+---+---+---+---+

Fen: 8/8/8/8/8/8/2k5/rR4K1 w B - 0 1
Key: 241D8337F3F980E1
Checkers: 

Position: 1/1
b1a1: 1
b1c1: 1
b1d1: 1
b1e1: 1
b1f1: 1
g1h2: 1
g1g2: 1
g1f2: 1
g1h1: 1
g1f1: 1

===========================
Total time (ms) : 7
Nodes searched  : 10
Nodes/second    : 1428
```

Expected: After castling kings are touching, so the attack from a1 is irrelevant. `g1b1` should be legal.

The problem is likely due to this check: https://github.com/ddugovic/Stockfish/blob/master/src/movegen.cpp#L66-L70

### PR DESCRIPTION
**Pull request by ianfab**
See #348.

### CODE REVIEW

**Comment by niklasf** [comment]
Is it intented that castling is not allowed in a situation like this?
```
 +---+---+---+---+---+---+---+---+
 |   |   | k |   |   |   |   |   |
 +---+---+---+---+---+---+---+---+
 | r | R |   |   |   |   | K |   |
 +---+---+---+---+---+---+---+---+
```

Going by

> I assume that the king moves first, and as it moves (through each square) it cannot move through check (unless adjacent to the opposing king); then the rook moves.

I think it should be.

**Comment by ddugovic** [comment]
For reference, my (embarrassing) second attempt is d08a843b31bed9df2fc0bf38cbbc6d9c1a6dca73 although somehow it also fails that Atomic960 use case.

**Comment by ddugovic** [comment]
Oops, my second attempt actually passes:

```
setoption name UCI_Variant value atomic
setoption name UCI_Chess960 value true
position fen 8/8/8/8/8/8/2k5/rR4K1 w Q - moves g1b1
d
```

**Comment by ianfab** [comment]
@niklasf Good point. I have slightly modified the code to take account of this.

**Comment by niklasf** [comment]
Looks good to me.

**Comment by ddugovic** [comment]
Thanks, looks good to me as well.

**Pull request merged**
